//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FussballManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public int Height { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> PlayerNmbr { get; set; }
        public int Position_ID { get; set; }
        public int PlayedGames { get; set; }
        public int Goals { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> Team_ID { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblTeam tblTeam { get; set; }
    }
}
