//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_1_GLUEFTUNG.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEngineLog1
    {
        public int ID { get; set; }
        public string ActCurrent { get; set; }
        public string ActPower { get; set; }
        public string ActSpeed { get; set; }
        public string ActVoltage { get; set; }
        public string ActDate { get; set; }
    }
}
